### ISSUE TITLE
Real case of Tradaboost

### ISSUE THREAD

**Issue by ToniaPf** [adapt-python/adapt#40]
Hello! 
I am trying to reproduce [Boosting for Transfer Learning](https://cse.hkust.edu.hk/~qyang/Docs/2007/tradaboost.pdf) using Tradaboost from this repository, but I fail to achieve the reported accuracy.
Is it possible that you have tested the implementation in a real dataset and that you could share the code or results, in order to understand if I'm doing something wrong?

**Comment by antoinedemathelin** [comment]
Hello ToniaPf,
Thank you for your interest in the ADAPT library! We currently haven't try to reproduce the experiments of TrAdaBoost but we will investigate this and come back to you as soon as possible!
Best,

**Comment by antoinedemathelin** [comment]
Hello @ToniaPf,

You can find an example of how to reproduce the TrAdaBoost experiment here: https://adapt-python.github.io/adapt/examples/tradaboost_experiments.html !

We have tried to reproduce the TrAdaBoost experiment and we found that we were able to reproduce the results only when using the probability of the classifier (between [0, 1]) as output instead of the prediction of the class (in {0, 1}).

Indeed, when using the prediction of the class, as the first estimator have alrady a 100% on the small target sample, the target error computed is 0 and there is no update of the sample weights. To avoid that we use the prediction of the classifier so we get an error > 0.

This was not explicitely stated in the paper, the only reference to that can be found in Algorithm 1 (end of step 2) in [Boosting for transfer learning](https://cse.hkust.edu.hk/~qyang/Docs/2007/tradaboost.pdf).

![image](https://user-images.githubusercontent.com/45264923/162784531-6bbf8f35-f635-4561-9632-9ae17613c90f.png)

Thank you for noticing this issue with TrAdaBoost!
Best,

**Comment by ToniaPf** [comment]
Thank you @antoinedemathelin

**Comment by ToniaPf** [comment]
Hello,
i am trying to understand why we have worse performance when using e.g 50 Estimators compared to 10.
Authors indicate that: "TrAdaBoost does not converge well until at least 50 iterations."
This is also what i would expect when increasing performance... The error to  decrease when the estimators are increased let's say up to 50-60 and after this number the improvement to be insignificant.

**Comment by antoinedemathelin** [comment]
Hi @ToniaPf,
This is a good question, we don't know why we are not able to reproduce the results on 20 NewsGroup with 100 estimators (used in the paper) instead of 10 (used in the notebook).

When investigating a little bit, it appears that, when too many estimators are used, the total weights on source goes to zero and the total weights on target goes to one (As in the figure below):

![image](https://user-images.githubusercontent.com/45264923/164230956-13cfc115-8b41-4b7e-a513-c327ae5d5fbb.png)

At the end, only the last half of the estimators (the 50 last estimators) are used for the predictions. Here they are all "Target Only" models as they are fitted with a total target weight of 1 and a total source weight of 0.

In fact, this behavior is known for TradaBoost for regression (see [Pardoe's paper](https://www.cs.utexas.edu/~dpardoe/papers/ICML10.pdf)). The authors state that, as the error is not zero for the source instances, the total weight of source will go to zero when the number of estimators increases. This behavior would not happen, if we use the prediction (in {0, 1}) of the models instead of the confidence prediction (in [0, 1]). However, as stated in the previous message, we have seen that using the prediction in {0, 1} failed because the weights are not updating. This is due to the fact that the first model already predict perfectly all instances (total accuracy is 100%). We are then stuck to the "Source Only" model...

We don't know what we should do... As far as we know, the authors didn't report this problem. We choose for know to use the confidence prediction as we are able to have good results in that way, but one needs to choose the right number of estimators...

Notice that there is a `lr` parameter that can be used to smooth the weights update, by default `lr = 1` but for example when using `lr=0.25` we get:

![image](https://user-images.githubusercontent.com/45264923/164235687-47a10b07-50cf-4e49-9ab7-50dca8ae9138.png)

Tuning the `lr` parameter can lead to better results
