### ISSUE TITLE
String formating of methods through error

### ISSUE THREAD

**Issue by antoinedemathelin** [adapt-python/adapt#90]
```pyhton
kliep = KLIEP(estimator=Ridge(), Xt=X_tgt)

kliep.fit(X_train, y_train)
```

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by Nodanoda-kun** [comment]
I have the same error.  It seems that KLIEP cannot execute `__repr__` function. 
This is because KLIEP class has np.array argument as default initial parameters. 
(See this line in sklean. https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/_pprint.py#L101)

Solution1: use [1e-3, 1e-2, 1e-1, 1, 10] as default value instead of np.logspace(-3, 1, 5)
Solution2: change the default value to None, and replace np.logspace(-3, 1, 5) in the `__init__` function.

I hope this will help.

**Comment by antoinedemathelin** [comment]
Thank you @Nodanoda-kun,

We are going to add your modification for the next release.

Best,
